root: /mvcskel/

dsn: mysql://root:@localhost/mvcskel

logger:
    name: tmp/log.txt
    level: 7
    handler: file

nice-urls: true

email-from: nobody@mvcskel.org

smarty-compile-check: 1

version: set_current_revno
